services:
  backend:
    build: ./backend
    restart: unless-stopped
    dns: # <-- ДОБАВЛЯЕМ ЭТУ СЕКЦИЮ
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./database_data:/app/database
      - ./backend/amocrm/amocrm.json:/app/amocrm/amocrm.json
    environment:
      - NODE_ENV=production # <-- Говорим, что это продакшен

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:80"
