services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Добавляем аргумент для принудительной пересборки
      args:
        - BUILD_VERSION=${BUILD_VERSION:-latest}
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./persistent_data:/app/persistent_data  # Общий volume для всех данных
      #- ./backend/amocrm/amocrm.json:/app/amocrm/amocrm.json:ro  # Только чтение
      - tokens_volume:/app/tokens  # Отдельный volume для токенов
    environment:
      - NODE_ENV=production
      - STORAGE_PATH=/app/persistent_data
      - TOKENS_PATH=/app/tokens
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Добавляем аргумент для принудительной пересборки при каждом деплое
      args:
        - BUILD_VERSION=${BUILD_VERSION:-$(date +%s)}
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_VK_APP_ID=54020028
      - VITE_API_URL=https://api.5425685-au70735.twc1.net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # depends_on:
    #   - backend

volumes:
  tokens_volume:
    driver: local
