name: Deploy with Docker

on:
  workflow_dispatch: # Ручной запуск
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via SSH with Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /var/www/farolero-loyalty-app
          
          # Остановить контейнеры
          docker-compose down
          
          # Получить последние изменения
          git pull origin main
          
          # Пересобрать и запустить контейнеры
          docker-compose build --no-cache
          docker-compose up -d
          
          # Проверить статус
          docker-compose ps
          
          # Показать логи для проверки
          docker-compose logs --tail=50
          
          echo "✅ Docker deployment completed!"
